name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read # Use with `only-new-issues` option.

env:
  GO_VERSION: 1.26

jobs:
  golangci:
    name: check-linter
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false # golangci-lint maintains its own cache
      - name: set golangci-lint version # keep in sync with tools/go.mod
        run: |
          echo "GOLANGCI_LINT_VERSION=$(cd tools; go list -m -f '{{ .Version }}' github.com/golangci/golangci-lint)" >> "$GITHUB_ENV"
      - name: golangci-lint
        uses: step-security/golangci-lint-action@1797facf9ea427614d729a4e9cab0fae1a7852d9 # v9.2.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          only-new-issues: true
